#!/bin/bash
#
# boostrap install things.

cd "$(dirname "$0")/.."
DOTFILE_ROOT=$(pwd)

set -e

echo ''

info() {
  printf "  [ \033[00;34m..\033[0m ] $1"
}

user() {
  printf  "\r  [ \033[00;34m..\033[0m ] $1"
}

success() {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}
