#!/bin/bash
#
# Run all dotfiles installer
set -e
cd "(dirname $0)"/..

# find the installers and run them interatively
find . -name install.sh | while read installer ; do sh -C "${installer}" ; done
